--11/07_2

--데이터 무결성과 제약조건
--제약조건
--테이블에 유효하지않은 (부적절한) 데이터가 입력되는 것을 방지
--테이블 생성시점시

/*
NOT NULL NULL값 포함하지 못하게
UNIQUE 모든 로우에 대해서 유일한 값을 갖도록함
PRIMARY KEY 중복된 값과 NULL을 모두 허용하지 않음
FOREIGN KEY 참조되는 테이블에 칼럼 값이 항상 존재해야함 NULL값은 안된다 (NOT NULL + UNIQUE)
CHECK 저장 가능한 데이터 값의 범위와 조건을 지정하여 설정된 값만 허용
*/

/*NOT NULL*/
CREATE TABLE customer (
ID VARCHAR2(20) NOT NULL,
pwd VARCHAR2(20) NOT NULL,
NAME VARCHAR2(20) NOT NULL,
phone VARCHAR2(30),
address VARCHAR2(100));

--오류 : ORA-01400: NULL을 ("TEST"."CUSTOMER"."ID") 안에 삽입할 수 없습니다
INSERT INTO customer VALUES (NULL,NULL,NULL,'010-111-1111','SEOUL');
INSERT INTO customer VALUES ('','','','010-111-1111','SEOUL');
--이렇게 하면 들어감 하지만 이렇게해서는 안된다
INSERT INTO customer VALUES (' ',' ',' ','010-111-1111','SEOUL');

--UNIQUE 특정 칼럼에 모든값이 고유하게 유지되도록 하는 고유키를 생성 
--오라클의 경우 고유키에 의해 인덱스를 함시적으로 생성

CREATE TABLE CUSTOMER (
ID VARCHAR2(20) UNIQUE,
PWD VARCHAR2(20) NOT NULL,
NAME VARCHAR2(20) NOT NULL,
PHONE VARCHAR2(30),
ADDRESS VARCHAR2(100));

--제약조건에 이름을 지정 CONSTRAINT 제약조건이름 제약조건
CREATE TABLE CUSTOMER (
ID VARCHAR2(20) CONSTRAINT CUSTOMER_ID_UK UNIQUE,
PWD VARCHAR2(20) CONSTRAINT CUSTOMER_PWD_NN NOT NULL,
NAME VARCHAR2(20) CONSTRAINT CUSTOMER_NAME_NN NOT NULL,
PHONE VARCHAR2(30),
ADDRESS VARCHAR2(100));

--데이터 사전?

--PRIMARY KEY
--테이블에 기본키 생성
--중복된 데이터를 저장 하지 못하는 고유성이 부여됨
--NULL 값을 가질수 없음 
--테이블의 모든 로우를 구별하기위한 식별자를 정의

--기본키 PRIMARY KEY 설정
--CONSTRAINT 명시 - 제약조건의 이름을 쓸경우
CREATE TABLE CUSTOMER (
ID VARCHAR2(20) ,
PWD VARCHAR2(20) NOT NULL,
NAME VARCHAR2(20) NOT NULL,
PHONE VARCHAR2(30),
ADDRESS VARCHAR2(100),
CONSTRAINT CUSTOMER_ID_PK PRIMARY KEY(ID));

--CONSTRAINT - 제약조건의 이름을 쓰지 않을 경우 (제약조건의 이름은 오라클에서 자동으로 부여)
CREATE TABLE CUSTOMER (
ID VARCHAR2(20) PRIMARY KEY,
PWD VARCHAR2(20) NOT NULL,
NAME VARCHAR2(20) NOT NULL,
PHONE VARCHAR2(30),
ADDRESS VARCHAR2(100));

--FIREIGN KEY 참조키
--참조 무결성은 테이블과 테이블 사이의 주종관계 설정을 위한 제약조건

--FIREIGN KEY 생성   CONSTRAINT ~ REFERENCES ~  반드시 필요하다
CREATE TABLE EMP_SECOND (
ENO NUMBER(4) CONSTRAINT EMP_SECOND_ENO_PK PRIMARY KEY ,
ENAME VARCHAR2(10),
JOB VARCHAR2(9),
DNO NUMBER(4) CONSTRAINT EMP_SECOND_DNO_FK REFERENCES DEPARTMENT);

DROP TABLE EMP_SECOND;

CREATE TABLE EMP_SECOND (
ENO NUMBER(4) CONSTRAINT EMP_SECOND_ENO_PK PRIMARY KEY ,
ENAME VARCHAR2(10),
JOB VARCHAR2(9),
DNO NUMBER(4) REFERENCES DEPARTMENT);

--CHECK
--컬럼에서 허용가능한 데이터의 점위나 조건을 정의
--설정된 이외의 값이 들어오면 오류메세지와 함께 명령을 수행하지 못하게 함
--CHECK 제약 조건의 수는 제한이 없다 CURRVAL,NEXTVAL,ROWNUM 같은 의사 컬럼 SYSDATE,USER 와 같은 함수에는 사용 못함 

CREATE TABLE EMP_SECOND(
ENO NUMBER(4) CONSTRAINT EMP_SECOND_ENO_PK PRIMARY KEY,
ENAME VARCHAR2(10),
SALARY NUMBER(4) CONSTRAINT EMP_SECOND_SALARY_MIN CHECK (SALARY >0));

CREATE TABLE CUSTOMER_2 (
ID VARCHAR2(20) NOT NULL CHECK(ID NOT IN(' ')) PRIMARY KEY,
PWD VARCHAR2(20) NOT NULL CHECK(PWD NOT IN(' ')),
NAME VARCHAR2(20) NOT NULL CHECK(NAME NOT IN(' ')),
PHONE VARCHAR2(30),
ADDRESS VARCHAR2(100));

INSERT INTO customer_2 VALUES (' ',' ',' ','010-111-1111','SEOUL');

/*DEFAULT 
    어떤 값도 입력하지 않았을때 DEFAULT 값이 입력됨 */
DROP TABLE EMP_SECOND;

CREATE TABLE EMP_SECOND(
ENO NUMBER(4) CONSTRAINT EMP_SECOND_ENO_PK PRIMARY KEY,
ENAME VARCHAR2(10),
SALARY NUMBER(7,2) DEFAULT 1000);

--오류: ORA-00947: 값의 수가 충분하지 않습니다
INSERT INTO EMP_SECOND VALUES (1111,'앤디');
--컬럼명을 명시하지 않을경우 모든 데이터를 입력해야한다
INSERT INTO EMP_SECOND (ENO,ENAME) VALUES (1111,'앤디');

--제약 조건의 추가 
--ALTER ADD CONSTRAINT
--제약 조건의 제거 
--ALTER DROP CONSTRAINT
--일시적으로 제약 조건 없애기
--ENABLE, DISABLE
 
/**/
--데이터 무결성
